LIB = $(BASE)/lib
SITE = $(BASE)/../OpenMath.github.io
INSTALL = $(SITE)/$(HERE)

STS = $(shell ls *.sts)
HTML = $(STS:%.sts=%.xhtml)
SAXON = java -jar $(LIB)/saxon/saxon9he.jar

all: $(HTML) 

$(HTML): %.xhtml: %.sts $(LIB)/xsl/sts2html.xsl
	xsltproc -o $@ $(LIB)/xsl/sts2html.xsl $<

install: all
	mkdir -p $(INSTALL) || true
	cp *.xhtml *.sts $(INSTALL)

echo:
	@echo $(HTML)
