LIB = $(BASE)/lib
SITE = $(BASE)/../OpenMath.github.io
INSTALL = $(SITE)/sts

STS = $(shell ls *.sts)
HTML = $(STS:%.sts=%.html)
SAXON = java -jar $(LIB)/saxon/saxon9he.jar

all: $(HTML) 

$(HTML): %.html: %.sts $(LIB)/xsl/sts2html.xsl
	$(SAXON) -o:$@ $< $(LIB)/xsl/sts2html.xsl 

install: all
	mkdir -p $(INSTALL) || true
	cp *.html *.sts $(INSTALL)

echo:
	@echo $(HTML)
