LIB = $(BASE)/lib
SITE = $(BASE)/../OpenMath.github.io
INSTALL = $(SITE)/cd

OCD = $(shell ls *.ocd)
HTML = $(OCD:%.ocd=%.html)
OMCD = $(OCD:%.ocd=%.omcd)
SAXON = java -jar $(LIB)/saxon/saxon9he.jar

all: $(HTML) $(OMCD)

$(HTML): %.html: %.ocd $(LIB)/xsl/cd.xsl
	$(SAXON) -s:$< -xsl:$(LIB)/xsl/cd.xsl -o:$@

$(OMCD): %.omcd: %.ocd $(LIB)/xsl/cd2om.xsl
	$(SAXON) -o:$@ $< $(LIB)/xsl/cd2om.xsl 

install: all
	mkdir -p $(INSTALL) || true
	cp *.html *.ocd *.omcd $(INSTALL)

echo:
	@echo $(HTML)
